---
title: "Lesson 4 notebook"
output: html_notebook
---


load diamonds dataset.
```{r}
library(ggplot2)
d <- diamonds
summary(diamonds)
```

practice histograms
```{r}
ggplot(aes(x = price), data = d)+
  geom_histogram(binwidth = 30)
```


price less than 500,250

```{r}
sum(d$price < 500)
sum(d$price < 250)
sum(d$price >= 15000)
```

explore the largest peak
```{r}
ggplot(aes(x=price), data = d)+
  geom_histogram(binwidth = 10)+
  scale_x_continuous(limits = c(0,1500), breaks = seq(0,1500,100))
ggsave('cheap_diamonds.png')
```


break out the diamond price by cut.
```{r}
ggplot(aes(x = price), data = d)+
  geom_histogram()+
  facet_wrap(~cut)
options(digits = 8)
by(d$price,d$cut,summary)
by(d$price, d$cut, summary, digits = max(getOption('digits')))
```

free scales
```{r}
ggplot(aes(x = price), data = d)+
  geom_histogram()+
  facet_wrap(~ d$cut,scales = 'free')
```

show prices by cut, transfer to log10
```{r}
ggplot(aes(x = price/carat), data = d)+
  geom_histogram(binwidth = 0.01)+
  facet_wrap(~cut, scales = 'free')+
  scale_x_log10()
```

```{r}
ggplot(aes(x=cut, y = price),data = d)+
  geom_boxplot()
ggplot(aes(x=clarity, y = price),data = d)+
  geom_boxplot()
ggplot(aes(x=color, y = price),data = d)+
  geom_boxplot()
```

IQR

```{r}
by(d$price,d$color,summary)
IQR(subset(d,color == 'D')$price)
IQR(subset(d,color == 'J')$price)
```

boxplot for different colors
```{r}
ggplot(aes(x = color, y = price/carat), data = d)+
  geom_boxplot()
```

Gapminder data
```{r}
pop <- read.csv('smoking.csv')#,header = T, row.names = 1, check.names = F)
pop<-t(pop)


```

